apiVersion: v1
data:
  DB_NAME: dms_microservice_dev
  DB_PASSWORD: P%40ssw0rd
  DB_PORT: "1433"
  DB_SERVER: 10.1.32.65
  DB_USER: imsi_raw
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dms-general-app--env
  name: app--env
