---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: dms-general
  name: dms-general
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dms-general
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/general-master-py-latest-default: "true"
        io.kompose.service: dms-general
    spec:
      containers:
        - args:
            - bash
            - -c
            - cd app && uvicorn main:app --host 0.0.0.0
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: app--env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: app--env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: app--env
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER
                  name: app--env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: app--env
          image: richardoalvin/general-service:v1.0
          name: dms-general
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: dms-general-claim0
      restartPolicy: Always
      volumes:
        - name: dms-general-claim0
          persistentVolumeClaim:
            claimName: dms-general-claim0
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dms-general-claim0
  name: dms-general-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: dms-general
  name: dms-general
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: dms-general
status:
  loadBalancer: {}

---

apiVersion: v1
data:
  DB_NAME: dms_microservice_dev
  DB_PASSWORD: P%40ssw0rd
  DB_PORT: "1433"
  DB_SERVER: 10.1.32.65
  DB_USER: imsi_raw
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dms-general-app--env
  name: app--env

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: general-master-py-latest-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/general-master-py-latest-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/general-master-py-latest-default: "true"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: dms-general-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/host/directory