apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: dms-general
  name: dms-general
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dms-general
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/general-master-py-latest-default: "true"
        io.kompose.service: dms-general
    spec:
      containers:
        - args:
            - bash
            - -c
            - cd app && uvicorn main:app --reload --host 0.0.0.0
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: app--env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: app--env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: app--env
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: DB_SERVER
                  name: app--env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: app--env
          image: draconacr.azurecr.io/dms-general:latest
          name: dms-general
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: dms-general-claim0
      restartPolicy: Always
      volumes:
        - name: dms-general-claim0
          persistentVolumeClaim:
            claimName: dms-general-claim0
status: {}
