from sqlalchemy import CHAR,String,Integer,Boolean, Column,ForeignKey,DateTime,Float
from sqlalchemy.orm import relationship
from configs.database import Base,engine

class MtrCompany(Base):
    __tablename__ = "mtr_company"
    is_active = Column(Boolean,nullable=False,default="True")
    company_id = Column(Integer,nullable=False,primary_key=True,autoincrement=True)
    company_code = Column(String(10),nullable=False,unique=True,default="")
    company_type = Column(CHAR(1),nullable=False)
    company_name = Column(String(100),nullable=False)
    company_abbreviation = Column(String(15),nullable=False,default="")
    #company_office_address_id = Column(Integer,ForeignKey("mtr_address.address.id"))
    company_phone_number = Column(String(30),nullable=True,default="")
    company_fax_number = Column(String(30),nullable=True,default="")
    company_email = Column(String(128),nullable=True,default="")
    vat_same_company_id = Column(Integer,nullable=True)
    vat_npwp_no = Column(String(35),nullable=False)
    vat_npwp_date = Column(DateTime,nullable=False)
    #vat_tax_out_transaction_id = Column(Integer,ForeignKey("mtr_tax_out_transaction.tax_out_transaction_id"))
    vat_tax_branch_code = Column(String(10),nullable=True,default="")
    vat_name = Column(String(100),nullable=True,default="")
    #vat_address_id = Column(Integer,ForeignKey("mtr_address.address.id"))
    vat_reserve = Column(CHAR(1), nullable=True,default="")
    vat_pkp_type = Column(CHAR(1),nullable=True,default="")
    vat_pkp_no = Column(String(30),nullable=True,default="")
    vat_pkp_date = Column(DateTime,nullable=True,default="")
    #vat_kpp_id = Column(Integer,ForeignKey("mtr_kpp.kpp_id"))
    tax_npwp_no = Column(String(30),nullable=False)
    tax_npwp_data = Column(DateTime,nullable=True,default="")
    #tax_address_id = Column(Integer,ForeignKey("mtr_address.address_id"))
    tax_pkp_type = Column(CHAR(1),nullable=True,default="")
    tax_pkp_no = Column(String(30),nullable=True,default="")
    tax_pkp_date = Column(DateTime,nullable=True,default="")
    #tax_kpp_id = Column(Integer,ForeignKey("mtr_kpp.kpp_id"))
    #region_id = Column(Integer,ForeignKey("mtr_region.region_id"))
    #finance_area_id = Column(Integer,ForeignKey("mtr_finance_area.finance_area_id"))
    #area_id = Column(Integer,ForeignKey("mtr_area.area_id"))
    #incentive_group_id = Column(Integer,ForeignKey("mtr_incentive_group.incentive_group_id"))
    #aftersales_area_id = Column(Integer,ForeignKey("mtr_aftersales_area.aftersales_area_id"))
    #company_ownership_id = Column(Integer,ForeignKey("mtr_company_ownership_id.company_ownership_id"))
    #business_category_id = Column(Integer,ForeignKey("mtr_business_category.business_category_id"))
    #term_of_payment_id = Column(Integer,ForeignKey("mtr_term_of_payment.term_of_payment_id"))
    company_dealer_kia_code = Column(String(10),nullable=True,default="")
    company_no_of_stall = Column(Float,nullable=True,default=0)
    is_distributor = Column(Boolean,nullable=True,default=False)

    #area = relationship("MtrArea",back_populates="mtr_company")